### ISSUE TITLE
looking for a freelance consultant BDR

### ISSUE THREAD

**Issue by axel20110** [2ndQuadrant/bdr-postgres#3]
I'm not sure if this is the right place, but I'm looking for a freelance consultant with very good BDR development know-how. We are considering whether to start a new project on this open source basis and are looking for appropriate technical support.
I would be happy to receive relevant messages and tips.

Regards
Axel

**Comment by rvanlaar** [comment]
Hi Axel,

We used the open source variant in production for quite some time. It's no longer maintained and the associated PostgreSQL version isn't supported anymore. 

 -Roland 
ps. I'm not affiliated with 2nd Quadrant

**Comment by martinmarques** [comment]
BDR 1.x which is the open source version is out of support (it's built on top of PG 9.4). If you want to try out BDR3, I suggest you get in touch with an EDB representative.

**Comment by axel20110** [comment]
Thx Roland, Martin,
I know about the status of this project. 
Therefore we are considering continuing the open source project and are therefore looking for people who are also interested in.

Regards
Axel
